export enum OperationType{
    ORDER_OPERATION_COMPLETED = 'ORDER_OPERATION_COMPLETED',
    ORDER_OPERATION_REJECTED = 'ORDER_OPERATION_REJECTED',
    ORDER_OPERATION_CANCELLED = 'ORDER_OPERATION_CANCELLED',
    STOCK_CREATED = 'STOCK_CREATED',
    STOCK_UPDATED = 'STOCK_UPDATED',
  }
  